openapi: '3.0.2'
info:
  title: Travel App API
  version: '1.0'
servers:
  - url: http://localhost:5000/
paths:
  /sights:
    get:
      description: 'sights'
      responses:
        '200':
          description: OK
  /rating:
    get:
      description: 'rating'
      responses:
        '200':
          description: OK
  /users:
    get:
      description: 'users'
      responses:
        '200':
          description: OK
  /countries:
    get:
      description: 'countries'
      responses:
        '200':
          description: OK
