openapi: '3.0.2'
info:
  title: Travel App API
  version: '1.0'
servers:
  - url: https://fierce-citadel-22012.herokuapp.com
  - url: http://localhost:5000/
paths:
  /countries:
    get:
      description: 'countries'
      responses:
        '200':
          description: OK
  /countries/id/{id}:
    get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      description: 'Get country by ID'
      responses:
        '200':
          description: OK
  /countries/sights/{sightId}:
    get:
      parameters:
        - in: path
          name: sightId
          required: true
          schema:
            type: string
      description: 'Get Comments by sightID'
      responses:
        '200':
          description: OK
